### ISSUE TITLE
How to use

### ISSUE THREAD

**Issue by Lartu** [kmck/nesify#1]
Hi there! I've been trying to execute `nesify` but to no avail, I cannot find a way to execute it. Could you by any chance tell me how can I build and execute this?

Thank you very much!

**Comment by kmck** [comment]
hi there! thanks for your interest. i've neglected this project a little bit and need to fix a few things and update the instructions, but try `npx babel-node cli.js` instead of `nesify`:

```bash
# on a mac, install pkg-config and other dependencies for the node canvas library
# if you run npm install and get errors, this is probably why
brew install pkg-config cairo libpng jpeg giflib
# install package dependencies
npm install
# install babel-cli since regular node doesn't support the es6 syntax used
npm install --save-dev babel-cli
# run the cli script, which is what nesify would do if it were installed
npx babel-node cli.js --srcUrl="http://whatever"
```

**Comment by Lartu** [comment]
Wonderful! Thank you very much!
